### ISSUE TITLE
urlgrabber.progress.TextMeter fails with "TypeError: '>' not supported between instances of 'NoneType' and 'int'"

### ISSUE THREAD

**Issue by jchax** [rpm-software-management/urlgrabber#24]
Description of problem:

Trying to use urlgrabber with a text progress meter fails with "TypeError: '>' not supported between instances of 'NoneType' and 'int'"

Version-Release number of selected component (if applicable):
 python3-urlgrabber-4.0.0-4.fc31

How reproducible: Always

Steps to Reproduce:
1.
Run this program:
~~~
#!/usr/bin/python3

from urlgrabber.grabber import URLGrabber
from urlgrabber.progress import TextMeter

g = URLGrabber(progress_obj=TextMeter())
g.urlgrab('https://download.fedoraproject.org/pub/fedora/linux/releases/31/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-31-1.9.iso')
~~~

(use a different URL if you prefer)

2. Wait a short while
3.

Actual results:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urlgrabber/grabber.py", line 1940, in _progress_update
    self.opts.progress_obj.update(downloaded)
  File "/usr/lib/python3.7/site-packages/urlgrabber/progress.py", line 149, in update
    self._do_update(amount_read, now)
  File "/usr/lib/python3.7/site-packages/urlgrabber/progress.py", line 251, in _do_update
    ave_dl = format_number(self.re.average_rate())
  File "/usr/lib/python3.7/site-packages/urlgrabber/progress.py", line 785, in format_number
    while number > thresh and depth < max_depth:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urlgrabber/grabber.py", line 1580, in _do_perform
    self.curl_obj.perform()
pycurl.error: (42, 'Callback aborted')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./grabber.py", line 7, in <module>
    g.urlgrab('https://download.fedoraproject.org/pub/fedora/linux/releases/31/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-31-1.9.iso')
  File "/usr/lib/python3.7/site-packages/urlgrabber/grabber.py", line 1256, in urlgrab
    return self._retry(opts, retryfunc, url, filename)
  File "/usr/lib/python3.7/site-packages/urlgrabber/grabber.py", line 1145, in _retry
    r = func(opts, *args)
  File "/usr/lib/python3.7/site-packages/urlgrabber/grabber.py", line 1241, in retryfunc
    fo = PyCurlFileObject(url, filename, opts)
  File "/usr/lib/python3.7/site-packages/urlgrabber/grabber.py", line 1343, in __init__
    self._do_open()
  File "/usr/lib/python3.7/site-packages/urlgrabber/grabber.py", line 1692, in _do_open
    self._do_grab()
  File "/usr/lib/python3.7/site-packages/urlgrabber/grabber.py", line 1826, in _do_grab
    self._do_perform()
  File "/usr/lib/python3.7/site-packages/urlgrabber/grabber.py", line 1615, in _do_perform
    raise KeyboardInterrupt
KeyboardInterrupt

Expected results:

A nice progress bar and, after a while, an iso.

Additional info:

I got 160KiB downloaded before the error message and nothing else was displayed at all. 

Although this is against Fedora31, I get the same error on Fedora 30 and using python2 instead of python3 everything works as expected both on Fedora31 and Fedora30.

**Comment by jchax** [comment]
Initialising ave_rate to zero instead of None in RateEstimator fixes that problem.   Changing "blen" to "int(blen)" in _term_add_bar() fixes the next one to show up.   Both of those are in /usr/lib/python3.7/site-packages/urlgrabber/progress.py

Hope that helps.

**Comment by jchax** [comment]
See also https://bugzilla.redhat.com/show_bug.cgi?id=1818842

**Comment by nikosmoum** [comment]
It's fixed, but it would be good to get it in an rpm or pypi release
